### PR TITLE
Update TopKFrequentNumbers.java

### PR DESCRIPTION
**Pull request by MAYANK816**
Is this code work for test case [ 5, 12, 11, 3, 11 ], 2 because on leetcode is getting submitted successful but for this test case it is showing answer is not unique, Please look in to this .

### CODE REVIEW

**Comment by MAYANK816** [comment]
I hope you will not ignore this.

**Comment by ndesai15** [comment]
Hello, @MAYANK816 I really appreciate your contribution to making this repo/code better. For sure I will look into this. But what made you think that I will ignore this? Because if you look at my all pull requests, I have responded to all pull requests.

**Comment by MAYANK816** [comment]
No, its nothing like that I am following all your videos but I just write it because sometimes we all are busy at work and ignore that So I think somebody is facing the same thought is seeking this type of solution and no offense buddy, love your content.I hope you understand.

**Comment by ndesai15** [comment]
I used the wrong example in `public static void main`. If you read LC problem constraint it is guaranteed to have a unique answer. I've corrected it. Thanx! BTW I am not the video maker person I am just one of the contributor for Java solutions.

**Comment by MAYANK816** [comment]
okay Thanks mate

**Pull request closed without merging**
