### PR TITLE
Solution: Generate Parentheses

### PR DESCRIPTION
**Pull request by 7mada123**
Added java solution for Generate Parentheses

### CODE REVIEW

**Comment by ndesai15** [comment]
Please also update the README file.

**Comment by 7mada123** [comment]
Sorry my bad, I will updated now.

**Comment by ndesai15** [comment]
@7mada123 Is this MR still active?

**Comment by 7mada123** [comment]
@ndesai15  yes
should I change something ?

**Review by 7mada123 — COMMENTED** [review]
added problems to README.md

**Comment by ndesai15** [comment]
Sorry but I have to close this MR as solution is already present in a repository.

**Pull request closed without merging**
