### PR TITLE
fixes for some edge cases failed

### PR DESCRIPTION
**Pull request by kumarmohit9648**
Test cases:
[1,1]
[2,3]

### CODE REVIEW

**Comment by ndesai15** [comment]
Closing this out as I have already updated code with working solution from my LC solutions.

**Comment by kumarmohit9648** [comment]
OK but it not working 
Please check once
because it failed in LC test cases.

**Comment by ndesai15** [comment]
Are you sure it is failing? Did you clone the latest master?
image

**Comment by kumarmohit9648** [comment]
I have checked with the latest master branch and it's working fine.
I came through your neetcode.io hyperlink so it gives the wrong solution.

**Pull request closed without merging**
